bib/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^synczotero/$', views.sync_zotero, name="synczotero"),
    url(r'^synczotero/result$', views.sync_zotero_action, name="synczotero_action")
]

seals/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from rest_framework import routers
from places.apis_views import PlaceViewSet
from bib.api_views import BookViewSet

from vocabs import api_views

router = routers.DefaultRouter()
router.register(r'skoslabels', api_views.SkosLabelViewSet)
router.register(r'skosnamespaces', api_views.SkosNamespaceViewSet)
router.register(r'skosconceptschemes', api_views.SkosConceptSchemeViewSet)
router.register(r'skosconcepts', api_views.SkosConceptViewSet)
router.register(r'places', PlaceViewSet)
router.register(r'Book', BookViewSet)

urlpatterns = [
    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('webpage.urls', namespace='webpage')),
    url(r'^vocabs/', include('vocabs.urls', namespace='vocabs')),
    url(r'^vocabs-ac/', include('vocabs.dal_urls', namespace='vocabs-ac')),
    url(r'^datamodel/', include('django_spaghetti.urls', namespace='datamodel')),
    url(r'places/', include('places.urls', namespace='places')),
    url(r'^bib/', include('bib.urls', namespace='bib')),
    url(r'^tablets/', include('tablets.urls', namespace='tablets')),
    url(r'^browsing/', include('browsing.urls', namespace='browsing')),
]

tablets/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^(?P<pk>[0-9]+)$', views.TabletDetailView.as_view(), name='tablet_detail'),
    url(r'^create/$', views.TabletCreate.as_view(), name='tablet_create'),
    url(r'^update/(?P<pk>[0-9]+)$', views.TabletUpdate.as_view(), name='tablet_update'),
    url(r'^delete/(?P<pk>[0-9]+)$', views.TabletDelete.as_view(), name='tablet_delete'),
    url(r'^seals/(?P<pk>[0-9]+)$', views.SealDetailView.as_view(), name='seal_detail'),
    url(r'^seals/create/$', views.SealCreate.as_view(), name='seal_create'),
    url(r'^seals/update/(?P<pk>[0-9]+)$', views.SealUpdate.as_view(), name='seal_update'),
    url(r'^seals/delete/(?P<pk>[0-9]+)$', views.SealDelete.as_view(), name='seal_delete'),
]

tablets/models.py
from django.db import models
from django.contrib.postgres.fields import JSONField
from django.core.urlresolvers import reverse
from places.models import Place
from vocabs.models import SkosConcept
from bib.models import Book


class Seal(models.Model):
    owner = models.ForeignKey(
        SkosConcept, blank=True, null=True, related_name="tablet_owner"
    )
    seal_type = models.ForeignKey(
        SkosConcept, blank=True, null=True, related_name="tablet_sealtype"
    )
    seal_motive = models.ForeignKey(
        SkosConcept, blank=True, null=True, related_name="tablet_motive"
    )
    seal_position = models.ForeignKey(
        SkosConcept, blank=True, null=True, related_name="tablet_position"
    )
    reference = models.ManyToManyField(
        Book, blank=True, related_name="tablet_seal_book"
    )
    custom_md = JSONField(blank=True, null=True)

    def __str__(self):
        return "{}".format(self.id)

    def get_absolute_url(self):
        return reverse('tablets:seal_detail', kwargs={'pk': self.id})


class Tablet(models.Model):
    place = models.ForeignKey(Place, blank=True, null=True)
    archive = models.ForeignKey(
        SkosConcept, blank=True, null=True,
        help_text="Archiv = Sammlung von Tafeln", related_name='tablet_archive')
    cdli_no = models.CharField(
        max_length=50, blank=True, verbose_name="CDLI no.", help_text="Nummer der Tafel in CDLI")
    nabucco_no = models.CharField(
        max_length=50, blank=True, verbose_name="NABUCCO no.",
        help_text="Nummer der Tafel in NABUCCO")
    museum_no = models.CharField(
        max_length=50, blank=True, verbose_name="Museum Number")
    scribe = models.ForeignKey(
        SkosConcept, blank=True, null=True, help_text="asdf", related_name="tablet_scribe")
    period = models.ForeignKey(
        SkosConcept, blank=True, null=True, related_name="tablet_period")
    year = models.IntegerField(blank=True, null=True)
    date_not_after = models.IntegerField(blank=True, null=True)
    date_not_before = models.IntegerField(blank=True, null=True)
    babyloneian_time = models.ForeignKey(
        SkosConcept, blank=True, null=True, related_name="tablet_babyloneian_time")
    date_comment = models.TextField(blank=True, null=True)
    text_type = models.ForeignKey(
        SkosConcept, blank=True, null=True, related_name="text_type")
    reference = models.ManyToManyField(
        Book, blank=True
    )
    seal = models.ManyToManyField(
        Seal, blank=True
    )
    custom_md = JSONField(blank=True, null=True)

    def __str__(self):
        return "{}".format(self.cdli_no)

    def get_absolute_url(self):
        return reverse('tablets:tablet_detail', kwargs={'pk': self.id})

tablets/forms.py
from dal import autocomplete
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from .models import Tablet, Seal


class GenericFilterFormHelper(FormHelper):
    def __init__(self, *args, **kwargs):
        super(GenericFilterFormHelper, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.form_class = 'genericFilterForm'
        self.form_method = 'GET'
        self.add_input(Submit('Filter', 'search'))


class SealForm(forms.ModelForm):
    class Meta:
        model = Seal
        fields = "__all__"
        widgets = {
            'owner': autocomplete.ModelSelect2(
                url='../../../vocabs-ac/skos-constraint-ac/?scheme=owner'),
            'seal_type': autocomplete.ModelSelect2(
                url='../../../vocabs-ac/skos-constraint-ac/?scheme=seal_type'),
            'seal_motive': autocomplete.ModelSelect2(
                url='../../../vocabs-ac/skos-constraint-ac/?scheme=seal_motive'),
            'seal_position': autocomplete.ModelSelect2(
                url='../../../vocabs-ac/skos-constraint-ac/?scheme=seal_position'),
        }

    def __init__(self, *args, **kwargs):
        super(SealForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = True
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-md-3'
        self.helper.field_class = 'col-md-9'
        self.helper.add_input(Submit('submit', 'save'),)


class TabletForm(forms.ModelForm):
    class Meta:
        model = Tablet
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super(TabletForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = True
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-md-3'
        self.helper.field_class = 'col-md-9'
        self.helper.add_input(Submit('submit', 'save'),)

tablets/views.py
from django.shortcuts import render
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse_lazy
from .models import Tablet, Seal
from .forms import TabletForm, SealForm

class SealDetailView(DetailView):

    model = Seal
    template_name = 'tablets/seal_detail.html'


class SealCreate(CreateView):

    model = Seal
    template_name = 'tablets/seal_create.html'
    form_class = SealForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(SealCreate, self).dispatch(*args, **kwargs)


class SealUpdate(UpdateView):

    model = Seal
    form_class = SealForm
    template_name = 'tablets/seal_create.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(SealUpdate, self).dispatch(*args, **kwargs)


class SealDelete(DeleteView):
    model = Seal
    template_name = 'vocabs/confirm_delete.html'
    success_url = reverse_lazy('browsing:browse_tablets')

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(SealDelete, self).dispatch(*args, **kwargs)


class TabletDetailView(DetailView):

    model = Tablet
    template_name = 'tablets/tablet_detail.html'


class TabletCreate(CreateView):

    model = Tablet
    template_name = 'tablets/tablet_create.html'
    form_class = TabletForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(TabletCreate, self).dispatch(*args, **kwargs)


class TabletUpdate(UpdateView):

    model = Tablet
    form_class = TabletForm
    template_name = 'tablets/tablet_create.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(TabletUpdate, self).dispatch(*args, **kwargs)


class TabletDelete(DeleteView):
    model = Tablet
    template_name = 'vocabs/confirm_delete.html'
    success_url = reverse_lazy('browsing:browse_tablets')

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(TabletDelete, self).dispatch(*args, **kwargs)

tablets/templates/tablets/seal_create.html
{% extends "webpage/base.html" %}
{% block Titel %} Create/Modify a Seal {% endblock %}
{% block content %}
{% load crispy_forms_tags %}

<div class="container">
<div class="panel panel-default procustom-panel-create">
    <div class="panel-heading procustom-panel-heading">
        <h1>Create/Edit Seal</h1>
        {% if object %}
            <ol class="breadcrumb">
                <li><a href="/">Home</a></li>
                <li class="active">{{ object }}</li>
            </ol>
      {% endif %}

    </div>
    <div class="panel-body">
        {% crispy form %}
    </div>
</div>
</div>

{% endblock content %}

tablets/templates/tablets/seal_detail.html
{% extends "webpage/base.html" %}
{% load staticfiles %}

{% block content %}
    <h1>
        Seal ID: {{ object.id }}
    </h1>

    <legend>Seal</legend>
    <table class="table table-bordered table-hover">
        <tr>
            <th class="col-sm-3">Owner</th>
            <td>{{object.owner}}</td>
        </tr>
        <tr>
            <th>Type</th>
            <td>{{ object.seal_type }}</td>
        </tr>
        <tr>
            <th>Motive</th>
            <td>{{ object.seal_motive }}</td>
        </tr>
        <tr>
            <th>Position on Tablet</th>
            <td>{{ object.seal_position }}</td>
        </tr>
    </table>

    <legend>References</legend>
    <table class="table table-bordered table-hover">
        {% for x in object.reference.all %}
            <tr>
                <th>Comment</th>
                <td>{{ x.reference }}</td>
            </tr>
        {% endfor %}
    </table>
    {% if user.is_authenticated %}
        <a class="btn btn-primary" href="{% url 'tablets:seal_update' pk=object.pk %}" role="button">edit seal</a>
        <a class ="btn btn-danger" href="{% url 'tablets:seal_delete' pk=object.id %}">delete</a>

    {% endif %}

{% endblock %}

tablets/templates/tablets/tablet_create.html
{% extends "webpage/base.html" %}
{% block Titel %} Create/Modify a Tablet {% endblock %}
{% block content %}
{% load crispy_forms_tags %}

<div class="container">
<div class="panel panel-default procustom-panel-create">
    <div class="panel-heading procustom-panel-heading">
        <h1>Create/Edit Tablet</h1>
        {% if object %}
            <ol class="breadcrumb">
                <li><a href="/">Home</a></li>
                <li class="active">{{ object }}</li>
            </ol>
      {% endif %}

    </div>
    <div class="panel-body">
        {% crispy form %}
    </div>
</div>
</div>

{% endblock content %}

tablets/templates/tablets/tablet_detail.html
{% extends "webpage/base.html" %}
{% load staticfiles %}
{% block scriptHeader %}
<!--leafletjs -->
    <link rel="stylesheet" href="{% static 'webpage/libraries/leaflet/leaflet.css' %}" />
    <script src="{% static 'webpage/libraries/leaflet/leaflet.js' %}"></script>
        <style>
            #map { height: 500px; }
        </style>

{% endblock %}
{% block content %}
    <h1>
        {{ object.cdli_no }} | {{ object.nabucco_no }} | {{ object.museum_no }}
    </h1>

    <legend>Tablet</legend>
    <table class="table table-bordered table-hover">
        <tr>
            <th class="col-sm-3">Place</th>
            <td>{{object.place}}</td>
        </tr>
        <tr>
            <th>Archive</th>
            <td>{{ object.archive }}</td>
        </tr>
        <tr>
            <th>Scribe</th>
            <td>{{ object.scribe }}</td>
        </tr>
        <tr>
            <th>Text Type</th>
            <td>{{ object.text_type }}</td>
        </tr>
    </table>
    <legend>Date</legend>
    <table class="table table-bordered table-hover">
        <tr>
            <th>Period</th>
            <td>{{ object.period }}</td>
        </tr>
        <tr>
            <th>Year</th>
            <td>{{ object.year }}</td>
        </tr>
        <tr>
            <th>Date not before | after</th>
            <td>
                {{ object.date_not_before }} | {{ object.date_not_after }}
            </td>
        </tr>
        <tr>
            <th>Babyloneian Time</th>
            <td>
                {{ object.babyloneian_time }}
            </td>
        </tr>
        <tr>
            <th>Comment</th>
            <td>{{ object.date_comment }}</td>
        </tr>
    </table>

    <legend>References</legend>
    <table class="table table-bordered table-hover">
        {% for x in object.reference.all %}
            <tr>
                <th>Comment</th>
                <td>{{ x.reference }}</td>
            </tr>
        {% endfor %}
    </table>


    <legend>Location {{ object.place }}</legend>
        {% if object.place.lat %}
            <div id="map"></div><br/>
        {% endif %}

        {% if user.is_authenticated %}
            <a class="btn btn-primary" href="{% url 'tablets:tablet_update' pk=object.pk %}" role="button">edit tablet</a>
            <a class ="btn btn-danger" href="{% url 'tablets:tablet_delete' pk=object.id %}">delete</a>

        {% endif %}
{% endblock %}
{% block scripts2 %}
    <script type="text/javascript">

        var gps1 = {{ object.place.lat }};
        var gps2 = {{ object.place.lng }};
        var map = L.map('map').setView([gps1, gps2], 6);

        L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
            attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
            maxZoom: 18,
            id: 'mapbox.light',
            accessToken: 'pk.eyJ1Ijoic2VubmllcmVyIiwiYSI6ImNpbHk1YWV0bDAwZnB2dW01d2l1Y3phdmkifQ.OljQLEhqeAygai2y6VoSwQ'
            }).addTo(map);

        L.marker([gps1 , gps2]).addTo(map)
        .bindPopup('<a href="#">{{ object.place.name }}</a>')
        .openPopup();

    </script>
{% endblock scripts2 %}